# Generated by Django 4.1.7 on 2023-03-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_whyus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whyus',
            name='icon',
        ),
    ]
