# Generated by Django 4.1.7 on 2023-03-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ourstory_awardimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardimages',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='awardimages',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
