# Generated by Django 4.1.7 on 2023-03-23 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teamcategory_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterUseFulInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('companyinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyinfo')),
            ],
            options={
                'verbose_name': 'Useful Info',
                'verbose_name_plural': 'Useful Info',
            },
        ),
    ]
