# Generated by Django 4.1.7 on 2023-03-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_team_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='route_map',
            field=models.ImageField(default='home.png', upload_to='tour'),
        ),
    ]
