# Generated by Django 4.1.7 on 2023-03-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tour_route_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='route_map',
            field=models.ImageField(upload_to='tour'),
        ),
    ]
