# Generated by Django 4.1.7 on 2023-03-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_tour_route_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
