# Generated by Django 4.1.7 on 2023-03-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_inquiry_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='phone',
        ),
    ]
