# Generated by Django 4.1.7 on 2023-03-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_inquiry_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=255)),
                ('dest_city', models.CharField(max_length=255)),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField()),
                ('passengers', models.IntegerField()),
                ('baggage', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('VIP', 'VIP')], max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.TextField(max_length=100)),
                ('additional_information', models.TextField()),
                ('payment', models.TextField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Flight Booking',
                'verbose_name_plural': 'Flight Booking',
            },
        ),
    ]
