# Generated by Django 4.1.7 on 2023-03-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_contact_flightbooking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
