# Generated by Django 4.1.7 on 2023-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_flightbooking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
