# Generated by Django 4.1.7 on 2023-03-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_flightbooking_additional_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trip_start_date', models.DateField()),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=255)),
                ('contact_number', models.CharField(help_text='Phone with country code', max_length=20)),
                ('emergency_contact_number', models.CharField(help_text='Phone with country code', max_length=20)),
                ('passport_no', models.CharField(max_length=50)),
                ('place_of_issue', models.CharField(max_length=255)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('no_of_people', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Trip Booking',
                'verbose_name_plural': 'Trip Booking',
            },
        ),
    ]
