# Generated by Django 4.1.7 on 2023-03-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_tourbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='emergency_contact_number',
            field=models.CharField(blank=True, help_text='Phone with country code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='package',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='trip_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
