# Generated by Django 4.1.7 on 2023-03-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_tourbooking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Phone with country code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='no_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
