# Generated by Django 4.1.7 on 2023-03-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_tourbooking_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
