# Generated by Django 4.1.7 on 2023-03-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_tourbooking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='price',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
