# Generated by Django 4.1.7 on 2023-03-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_tourbooking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='dest_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='from_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
