# Generated by Django 4.1.7 on 2023-04-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_flightbooking_dest_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'General Settings', 'verbose_name_plural': 'General Settings'},
        ),
    ]
